framework:
    workflows:
        backup:
            type: "state_machine"
            audit_trail:
                enabled: true
            marking_store:
                type: "method"
                property: "currentPlace"
            supports:
                - App\Entity\Backup
            initial_marking: initialized
            places:
                - initialized
                - start
                - dump
                - download
                - upload
                - cleanup
                - health_check
                - forget
                - backuped
                - failed
            transitions:
                start:
                    from: initialized
                    to: start
                dump:
                    from: start
                    to: dump
                download:
                    from: dump
                    to: download
                upload:
                    from: [start, download]
                    to: upload
                cleanup:
                    from: [start, upload]
                    to: cleanup
                health_check:
                    from: [start, cleanup]
                    to: health_check
                forget:
                    from: health_check
                    to: forget
                backuped:
                    from: forget
                    to: backuped
                failed:
                    from:
                        [
                            initialized,
                            start,
                            dump,
                            download,
                            upload,
                            health_check,
                            forget,
                            cleanup,
                        ]
                    to: failed
