services:
    postgres:
        container_name: cloudbkp-postgres
        image: postgres:16-alpine
        restart: on-failure
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-db}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-db}
            POSTGRES_DB: ${POSTGRES_DB:-db}
        ports:
            - "${DATABASE_PORT:-5432}:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    postgres_test:
        container_name: cloudbkp-postgres-test
        image: postgres:16-alpine
        restart: on-failure
        environment:
            POSTGRES_USER: ${POSTGRES_TEST_USER:-db_test}
            POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD:-db_test}
            POSTGRES_DB: ${POSTGRES_TEST_DB:-db_test}
        ports:
            - "${DATABASE_TEST_PORT:-8432}:5432"
        volumes:
            - postgres_test_data:/var/lib/postgresql/data

    phppgadmin_dev:
        container_name: cloudbkp-phppgadmin
        image: bitnami/phppgadmin-archived
        restart: on-failure
        environment:
            DATABASE_HOST: postgres
        ports:
            - "${PHPPGADMIN_PORT:-9080}:8080"

    minio:
        container_name: cloudbkp-minio
        image: minio/minio:latest
        restart: on-failure
        ports:
            - "${MINIO_PORT:-9000}:9000"
            - "${MINIO_CONSOLE_PORT:-9001}:9001"
        volumes:
            - minio_data:/data
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
        command: server --address ":9000" --console-address ":9001" /data

    redis:
        container_name: cloudbkp-redis
        image: redis:7-alpine
        restart: on-failure
        command: redis-server --requirepass ${REDIS_PASSWORD:-redis_password} --appendonly yes
        ports:
            - "${REDIS_PORT:-6379}:6379"

    mailhog:
        container_name: cloudbkp-mailhog
        image: mailhog/mailhog:latest
        restart: on-failure
        ports:
            - "${MAILHOG_PORT_SMTP:-1025}:1025"
            - "${MAILHOG_PORT_HTTP:-8025}:8025"

    assets:
        container_name: cloudbkp-assets
        restart: on-failure
        build:
            context: .
            dockerfile: ./docker/frankenphp/Dockerfile
            target: assets-dev
        volumes:
            - ".:/app:rw"

    php:
        container_name: cloudbkp-php
        restart: on-failure
        build:
            context: .
            dockerfile: ./docker/frankenphp/Dockerfile
            target: dev
        depends_on:
            - postgres
            - redis
            - assets
        volumes:
            - ".:/app:rw"
            - caddy_data:/data/caddy  # Persist SSL certificates
            - caddy_config:/config/caddy  # Persist configuration
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        ports:
            - "${HTTP_PORT:-80}:80"
            - "${HTTPS_PORT:-443}:443"

volumes:
    postgres_data:
    postgres_test_data:
    minio_data:
    caddy_data:
    caddy_config:
