version: "3.7"
services:
    postgres:
        container_name: cloudbkp-postgres
        image: postgres:12
        restart: on-failure
        environment:
            POSTGRES_USER: db
            POSTGRES_PASSWORD: db
            POSTGRES_DB: db
        ports:
            - "${DATABASE_PORT:-5432}:5432"

    postgres_test:
        container_name: cloudbkp-phppgadmin-test
        image: postgres:12
        restart: on-failure
        environment:
            POSTGRES_USER: db_test
            POSTGRES_PASSWORD: db_test
            POSTGRES_DB: db_test
        ports:
            - ${DATABASE_TEST_PORT:-8432}:5432

    phppgadmin_dev:
        container_name: cloudbkp-phppgadmin
        image: bitnami/phppgadmin
        restart: on-failure
        environment:
            DATABASE_HOST: postgres
        ports:
            - "${DATABASE_PORT:-9080}:8080"

    minio:
        container_name: cloudbkp-minio
        image: minio/minio
        restart: on-failure
        ports:
            - "${MINIO_PORT:-9000}:9000"
            - "${MINIO_CONSOLE_PORT:-9001}:9001"
        volumes:
            - minio:/data
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        command: server --address ":9000" --console-address ":9001" /data

    redis:
        container_name: cloudbkp-redis
        image: redis:5.0.8
        restart: on-failure
        command: >
            --requirepass redis_password
        ports:
            - "${REDIS_PORT:-6379}:6379"

    mailhog_dev:
        container_name: cloudbkp-mailhog
        image: mailhog/mailhog
        restart: on-failure
        ports:
            - ${MAILHOG_PORT_SMTP:-1025}:1025
            - ${MAILHOG_PORT_HTTP:-8025}:8025

    assets:
        container_name: cloudbkp-assets
        restart: on-failure
        user: ${DOCKER_USER:-1000}
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile.dev
            target: assets-dev
        volumes:
            - ".:/app:rw"
            - "build:/data/public/build/"
        ports:
            - ${ENCORE_PORT_HTTP:-8080}:8080

    php:
        container_name: cloudbkp-php
        restart: on-failure
        user: ${DOCKER_USER:-1000}
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
            target: dev
        depends_on:
            - postgres
            - redis
            - assets
        volumes:
            - ".:/app:rw"
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
    nginx:
        container_name: cloudbkp-nginx
        restart: on-failure
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile.dev
            target: nginx-dev
        depends_on:
            - php
        volumes:
            - ".:/app:ro"
            - "build:/data/public/build/"
        ports:
            - ${PHP_PORT_HTTP:-80}:80

volumes:
    build:
    minio:
