apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    {{- include "openstack-backup.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: php
  selector:
    app: php
    {{- include "openstack-backup.selectorLabels" . | nindent 4 }}
{{- if .Values.postgres.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    {{- include "openstack-backup.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: postgres
    {{- include "openstack-backup.selectorLabels" . | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    {{- include "openstack-backup.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: redis
    {{- include "openstack-backup.selectorLabels" . | nindent 4 }}