<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250201185301 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Reset sequences after the last ADD GENERATED BY DEFAULT AS IDENTITY';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("SELECT setval('backup_configuration_id_seq1',(SELECT GREATEST(MAX(id), nextval('backup_configuration_id_seq'), nextval('backup_configuration_id_seq1')) FROM backup_configuration))");
        $this->addSql("SELECT setval('backup_id_seq1',(SELECT GREATEST(MAX(id), nextval('backup_id_seq'), nextval('backup_id_seq1')) FROM backup))");
        $this->addSql("SELECT setval('host_id_seq1',(SELECT GREATEST(MAX(id), nextval('host_id_seq'), nextval('host_id_seq1')) FROM host))");
        $this->addSql("SELECT setval('log_id_seq1',(SELECT GREATEST(MAX(id), nextval('log_id_seq'), nextval('log_id_seq1')) FROM log))");
        $this->addSql("SELECT setval('osproject_id_seq1',(SELECT GREATEST(MAX(id), nextval('osproject_id_seq'), nextval('osproject_id_seq1')) FROM osproject))");
        $this->addSql("SELECT setval('storage_id_seq1',(SELECT GREATEST(MAX(id), nextval('storage_id_seq'), nextval('storage_id_seq1')) FROM storage))");
        $this->addSql("SELECT setval('user_id_seq1',(SELECT GREATEST(MAX(id), nextval('user_id_seq'), nextval('user_id_seq1')) FROM public.user))");
    }

    public function down(Schema $schema): void
    {
    }
}
