<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260513025246 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create api_client table for inventory API authentication.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE api_client (
          id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          name VARCHAR(255) NOT NULL,
          client_id VARCHAR(64) NOT NULL,
          secret VARCHAR(255) NOT NULL,
          enabled BOOLEAN DEFAULT true NOT NULL,
          last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
          created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          PRIMARY KEY (id)
        )');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_41B343D519EB6921 ON api_client (client_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE api_client');
    }
}
