<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250630211835 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "kubeconfig" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, kubeconfig TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5EB15B30989D9B62 ON "kubeconfig" (slug)');
        $this->addSql('ALTER TABLE backup_configuration ADD kube_namespace VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE backup_configuration ADD kube_resource VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE backup_configuration ADD kubeconfig_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE backup_configuration ADD CONSTRAINT FK_E53979C3A703277B FOREIGN KEY (kubeconfig_id) REFERENCES "kubeconfig" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_E53979C3A703277B ON backup_configuration (kubeconfig_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE "kubeconfig"');
        $this->addSql('ALTER TABLE backup_configuration DROP CONSTRAINT FK_E53979C3A703277B');
        $this->addSql('DROP INDEX IDX_E53979C3A703277B');
        $this->addSql('ALTER TABLE backup_configuration DROP kube_namespace');
        $this->addSql('ALTER TABLE backup_configuration DROP kube_resource');
        $this->addSql('ALTER TABLE backup_configuration DROP kubeconfig_id');
    }
}
