<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250201123658 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE backup ALTER id TYPE INT');
        $this->addSql('ALTER TABLE backup ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE backup_configuration ALTER id TYPE INT');
        $this->addSql('ALTER TABLE backup_configuration ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE backup_configuration ALTER os_instance_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN backup_configuration.os_instance_id IS \'\'');
        $this->addSql('ALTER TABLE host ALTER id TYPE INT');
        $this->addSql('ALTER TABLE host ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE log ALTER id TYPE INT');
        $this->addSql('ALTER TABLE log ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE osinstance ALTER id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN osinstance.id IS \'\'');
        $this->addSql('ALTER TABLE osproject ALTER id TYPE INT');
        $this->addSql('ALTER TABLE osproject ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE storage ALTER id TYPE INT');
        $this->addSql('ALTER TABLE storage ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE "user" ALTER id TYPE INT');
        $this->addSql('ALTER TABLE "user" ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE osinstance ALTER id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN osinstance.id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE "user" ALTER id TYPE INT');
        $this->addSql('ALTER TABLE "user" ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE backup ALTER id TYPE INT');
        $this->addSql('ALTER TABLE backup ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE storage ALTER id TYPE INT');
        $this->addSql('ALTER TABLE storage ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE "host" ALTER id TYPE INT');
        $this->addSql('ALTER TABLE "host" ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE backup_configuration ALTER id TYPE INT');
        $this->addSql('ALTER TABLE backup_configuration ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE backup_configuration ALTER os_instance_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN backup_configuration.os_instance_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE log ALTER id TYPE INT');
        $this->addSql('ALTER TABLE log ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE osproject ALTER id TYPE INT');
        $this->addSql('ALTER TABLE osproject ALTER id DROP IDENTITY');
    }
}
